### ISSUE TITLE
DraggableGrid layout breaks if data is in state and is updated

### ISSUE THREAD

**Issue by Lakston** [mgcrea/react-native-dnd#34]
I'm getting my item list from redux state, and onOrderChange, an action is dispateched, which updates the order in the store, the item list updates and the grid breaks.

This is because when the list updates, onOrderChange fires multiple times, with empty array, or partial ids array, and completely breaks the layout.

I made a simplified[ repro on snack](https://snack.expo.dev/zzp1qu0oW-YGcaBFaSToJ) where the data is in react state and on order change the data is updated

any help on how to solve this would be appreciated, I need to send an api request on order change, and then update the state, not sure if this is a bug or if there is a workaround.

**Comment by Lakston** [comment]
Also how do you run the project locally ? I tried npm and pnpm but none of the scripts work, I tried to patch the lib directly in my project to test stuff but it's not working.

I dont know if I need to implement the same refreshOffsets methods as in the Stack or if this is another bug, or if I just misunderstood the way it should be used, thanks for your help.

**Comment by mgcrea** [comment]
Hi, if you use the latest version (eg. `"@mgcrea/react-native-dnd": "2.5.1"`) the example works. Looks like it might have broke at some point.

To run locally for developing against the library requires you to link the library (using `npm link` or `pnpm link`) and then using a special metro plugin to properly support linked packages (using `@mgcrea/metro-plugin-linked-packages`):

- metro.config.js:

```js
// @ts-check
/* eslint-disable no-undef, @typescript-eslint/no-require-imports  */
const { getDefaultConfig, mergeConfig } = require("@react-native/metro-config");
const { getLinkedPackagesConfig } = require("@mgcrea/metro-plugin-linked-packages");

const defaultConfig = getDefaultConfig(__dirname);

/**
 * Metro configuration
 * @see https://reactnative.dev/docs/metro
 * @type {import('metro-config').MetroConfig}
 */
const config = {};

module.exports = mergeConfig(defaultConfig, getLinkedPackagesConfig(__dirname), config);
```

Then you can switch the import to `@mgcrea/react-native-dnd/src` to be able to tweak the library source code without having to rebuild every time.

Let me know if that works for you, will update the README accordingly since it's not trivial.

**Comment by Lakston** [comment]
Dude you are amazing ! I'll try to test that today if possible otherwise I'll check back on monday.
